### ISSUE TITLE
Two errors broke all, i quess..

### ISSUE THREAD

**Issue by NeonTaylor** [nickc01/WeaverCore#19]
Uhm... so i installed the Weaver core, I did everything according to the instructions. And when i create and start new project, console gives me this:
![20240417_160842](https://github.com/nickc01/WeaverCore/assets/167322694/9a398047-8bd6-4081-a51e-9a21a29a93e7)

I thought problem hiding here... but idk how to fix this:
![20240417_160723](https://github.com/nickc01/WeaverCore/assets/167322694/fbdbb75d-3cc1-420b-bf39-06fb1525e4dd)

My OS: Windows10
And no, i didnt change code.

**Comment by nickc01** [comment]
Can you go to Edit -> Project Settings:

![Project Settings](https://github.com/nickc01/WeaverCore/assets/12601671/2db69b96-cb39-4a09-b624-a2e72d331e53)

Go to the "Player" tab, and under "Other Settings", check to make sure that the "Api Compatibility Level" is set to ".Net 4.x". This should have been automatically set by WeaverCore, but I guess you may have found a bug where it doesn't do that.

![Api Compatibility Level](https://github.com/nickc01/WeaverCore/assets/12601671/f673e962-fd36-4244-9a8a-2d70001d3bb4)

**Comment by NeonTaylor** [comment]
> Can you go to Edit -> Project Settings:
> 
> ![Project Settings](https://private-user-images.githubusercontent.com/12601671/323307693-2db69b96-cb39-4a09-b624-a2e72d331e53.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMzNzYyMTgsIm5iZiI6MTcxMzM3NTkxOCwicGF0aCI6Ii8xMjYwMTY3MS8zMjMzMDc2OTMtMmRiNjliOTYtY2IzOS00YTA5LWI2MjQtYTJlNzJkMzMxZTUzLlBORz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE3VDE3NDUxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwMjMwNjYzZWVkNjczMThkOTU5MTVmYjkwOWMyMzc1N2QxZGU1NjdjN2Y0NWMyMmI2NzE1YjMyNzE3YTQ1ZmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qyTqRDVqr4QLGXz3-xFLOaz0WVl4S4RwOsWpJFtjU48)
> 
> Go to the "Player" tab, and under "Other Settings", check to make sure that the "Api Compatibility Level" is set to ".Net 4.x". This should have been automatically set by WeaverCore, but I guess you may have found a bug where it doesn't do that.
> 
> ![Api Compatibility Level](https://private-user-images.githubusercontent.com/12601671/323309499-f673e962-fd36-4244-9a8a-2d70001d3bb4.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMzNzYyMTgsIm5iZiI6MTcxMzM3NTkxOCwicGF0aCI6Ii8xMjYwMTY3MS8zMjMzMDk0OTktZjY3M2U5NjItZmQzNi00MjQ0LTlhOGEtMmQ3MDAwMWQzYmI0LlBORz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE3VDE3NDUxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFhZjQ2Y2U4M2VmNTgzNGM2NTFjMjIxNGUwZmE3N2YwNDEyMjk5MjJhYTczNTAyZTgwYTc2YTUzOTVjMWIxOGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.476bU_es5GAApiBf5Sm0jPEvyL6gcQcFy28iThIVckQ)

Oh... thats works! Thank you so much!
