### ISSUE TITLE
Accessing prefab?

### ISSUE THREAD

**Issue by nQvTgLrp** [nickc01/WeaverCore#21]
I created an object in Unity Editor with weavercore, and drag this object to Resources folder to make a prefab.
Then later I tried to use Resources.Load to fetch the prefab but I got nothing.

Is this expected maybe because somehow mod prefabs are separated from game prefabs? If so how do I get access to a prefab in scripts? I need to instantiate it in every scene so not possible to place it in unity editor every scene I guess

**Comment by nickc01** [comment]
Loading objects via the Resources folder doesn't work in WeaverCore, but WeaverCore does implement an alternative that's able to do nearly the same thing.

Here's the steps:
1: Select your prefab, and at the bottom of the inspector tab, set the prefab's "AssetBundle" to your mod's bundle (Here's an example from my "Corrupted Kin" Mod

![2024-05-08T13:40:08,008772897-05:00](https://github.com/nickc01/WeaverCore/assets/12601671/73ce9cf1-f761-47c4-a30f-6a2294fc0d4a)

2: Now that it's marked, you can load the prefab at any time using the WeaverAssets.LoadAssetFromBundle functions. Here's an example snippet:

![2024-05-08T13:45:26,557099888-05:00](https://github.com/nickc01/WeaverCore/assets/12601671/5d066381-230b-4794-a9e0-d016fb6239b2)

There are other variants of the function that allow you to specify the bundle name too. https://github.com/nickc01/WeaverCore/blob/develop/WeaverCore/Utilities/WeaverAssets.cs

**Comment by nQvTgLrp** [comment]
Thanks! this works very well!
