### ISSUE TITLE
Failed To Call constructor

### ISSUE THREAD

**Issue by Starly27** [nickc01/WeaverCore#4]
It says this in both IKG and Corrupted Kin, i have WeaverCore Downloaded and it still doesnt work

[ModLog 06 12 2022 (22 45 50).txt](https://github.com/nickc01/WeaverCore/files/8886966/ModLog.06.12.2022.22.45.50.txt)

**Comment by Starly27** [comment]
I Use Windows 10 btw

**Comment by nickc01** [comment]
Yeah, I have been notified of the issue about 5 days ago. I just haven't had the time to address it yet, although I should be able to look into it sometime within the next few days.
![WeaverCore Bug](https://user-images.githubusercontent.com/12601671/173268805-677cb74e-240a-4e17-a9d1-aaa3bdeb8c6e.PNG)

**Comment by nickc01** [comment]
The issue should now be fixed in the latest release : https://github.com/nickc01/WeaverCore/releases/tag/v1.1.0.1

Let me know if there are any issues with it

**Comment by Starly27** [comment]
Thank You, i really wanted to play IKG and Corrupted kin
