### ISSUE TITLE
Weavercore makes enemies no longer show Dream Nail dialogue

### ISSUE THREAD

**Issue by Exempt-Medic** [nickc01/WeaverCore#6]
Pretty sure it's because [this part][1] never calls <code>orig(self)</orig>

[1]: https://github.com/nickc01/WeaverCore/blob/983aec4bcdf0db220c5917719ed8964862384aaf/Other%20Projects~/WeaverCore.Game/WeaverCore.Game/Patches/EnemyDreamNailReaction_Patches.cs#L20

**Comment by nickc01** [comment]
Yeah, that's probably why. I'll try and get updated when I have a chance

**Comment by nickc01** [comment]
Just committed a quick and small update that adds an "orig(self)" call to the patch. Let me know if that fixes the issue:

https://github.com/nickc01/WeaverCore/blob/c7863ab70ce79c1252f373965ad2f05dee54dfd8/Other%20Projects%7E/WeaverCore.Game/WeaverCore.Game/Patches/EnemyDreamNailReaction_Patches.cs#L27

**Comment by Exempt-Medic** [comment]
Yup, it works just fine now!
